version: 2
jobs:
        build:
                docker:
                        - image: circleci/cci-demo-docker-primary:0.0.2
                working_directory: /go/src/github.com/circleci/cci-demo-docker

                environment:
                        TEST_RESULTS: /tmp/test-results 
                steps:
                        - checkout

                        - run:
                                name: Install Docker client
                                command: |
                                        set -x
                                        VER="17.03.0-ce"
                                        curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
                                        tar -xz -C /tmp -f /tmp/docker-$VER.tgz
                                        mv /tmp/docker/* /usr/bin
                        - run:
                                name: Set up docker
                                command: |
                                        if [[ $CIRCLE_SHELL_ENV == *"localbuild"* ]]; then
                                                echo "export docker='sudo docker'" >> $BASH_ENV
                                        else
                                                echo "export docker='docker'" >> $BASH_ENV
                                        fi

                        - run:
                                name: Install Docker Compose
                                command: |
                                        set -x
                                        #curl -L https://github.com/docker/compose/releases/download/1.25/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
                                        #apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AA8E81B4331F7F50
                                        #apt-get update
                                        #apt-get -y install python-pip
                                        #pip install --upgrade setuptools
                                        #pip install -U docker-compose
                                        curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

                                        chmod +x /usr/local/bin/docker-compose 
                        

                        - run:
                                name: Starting compose
                                command: | 
                                        set -x
                                        docker-compose up -d
                                        docker run --network container:contacts \
                                                appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/cpmtacts/test
