version: 2
jobs:
        build:
                docker:
                        - image: circleci/cci-demo-docker-primary:0.0.2
                        - image: node:latest
                        - image: mysql:latest


                steps:
                        - run:
                                name: Install Docker Compose
                                command: |
                                        set -x
                                        curl -L https://github.com/docker/compose/releases/download/1.25/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
                                        chmod +x /usr/local/bin/docker-compose 
                        - run:
                                name: Starting compose
                                command: | 
                                        set -x
                                        docker-compose up -d
                                        docker run --network container:contacts \
                                                appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/cpmtacts/test
